<?php
/**
 * CardPaymentResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * CardPaymentResponseTest Class Doc Comment
 *
 * @category    Class
 * @description The card payment response
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CardPaymentResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CardPaymentResponse"
     */
    public function testCardPaymentResponse()
    {
    }

    /**
     * Test attribute "merchant_account_ref"
     */
    public function testPropertyMerchantAccountRef()
    {
    }

    /**
     * Test attribute "response_code"
     */
    public function testPropertyResponseCode()
    {
    }

    /**
     * Test attribute "complementary_response_code"
     */
    public function testPropertyComplementaryResponseCode()
    {
    }

    /**
     * Test attribute "schedules"
     */
    public function testPropertySchedules()
    {
    }

    /**
     * Test attribute "stored_card"
     */
    public function testPropertyStoredCard()
    {
    }

    /**
     * Test attribute "response_message"
     */
    public function testPropertyResponseMessage()
    {
    }
}
