<?php
/**
 * Card3DsPaymentPutRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * Card3DsPaymentPutRequestTest Class Doc Comment
 *
 * @category    Class
 * @description The CardPayment Request for the PUT
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Card3DsPaymentPutRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Card3DsPaymentPutRequest"
     */
    public function testCard3DsPaymentPutRequest()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "merchant_site_id"
     */
    public function testPropertyMerchantSiteId()
    {
    }

    /**
     * Test attribute "payment_request_id"
     */
    public function testPropertyPaymentRequestId()
    {
    }

    /**
     * Test attribute "order_ref"
     */
    public function testPropertyOrderRef()
    {
    }

    /**
     * Test attribute "order_tag"
     */
    public function testPropertyOrderTag()
    {
    }
}
