<?php
/**
 * Card3DsPaymentResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * Card3DsPaymentResponseTest Class Doc Comment
 *
 * @category    Class
 * @description The card payment response
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Card3DsPaymentResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Card3DsPaymentResponse"
     */
    public function testCard3DsPaymentResponse()
    {
    }

    /**
     * Test attribute "card3ds_payment_request_id"
     */
    public function testPropertyCard3dsPaymentRequestId()
    {
    }

    /**
     * Test attribute "card3ds_redirection_data"
     */
    public function testPropertyCard3dsRedirectionData()
    {
    }

    /**
     * Test attribute "card_enrollment_response_code"
     */
    public function testPropertyCardEnrollmentResponseCode()
    {
    }

    /**
     * Test attribute "response_message"
     */
    public function testPropertyResponseMessage()
    {
    }
}
