<?php
/**
 * ConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConfigurationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Configuration"
     */
    public function testConfiguration()
    {
    }

    /**
     * Test attribute "culture"
     */
    public function testPropertyCulture()
    {
    }

    /**
     * Test attribute "form_type"
     */
    public function testPropertyFormType()
    {
    }

    /**
     * Test attribute "merchant_back_url"
     */
    public function testPropertyMerchantBackUrl()
    {
    }

    /**
     * Test attribute "merchant_home_url"
     */
    public function testPropertyMerchantHomeUrl()
    {
    }

    /**
     * Test attribute "merchant_notify_url"
     */
    public function testPropertyMerchantNotifyUrl()
    {
    }

    /**
     * Test attribute "merchant_return_url"
     */
    public function testPropertyMerchantReturnUrl()
    {
    }

    /**
     * Test attribute "payment_option_ref"
     */
    public function testPropertyPaymentOptionRef()
    {
    }

    /**
     * Test attribute "report_delay_in_days"
     */
    public function testPropertyReportDelayInDays()
    {
    }

    /**
     * Test attribute "user_agent"
     */
    public function testPropertyUserAgent()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }
}
