<?php
/**
 * LoanTermTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * LoanTermTest Class Doc Comment
 *
 * @category    Class
 * @description All loan term data
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LoanTermTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LoanTerm"
     */
    public function testLoanTerm()
    {
    }

    /**
     * Test attribute "loan_term_ref"
     */
    public function testPropertyLoanTermRef()
    {
    }

    /**
     * Test attribute "min_amount"
     */
    public function testPropertyMinAmount()
    {
    }

    /**
     * Test attribute "max_amount"
     */
    public function testPropertyMaxAmount()
    {
    }

    /**
     * Test attribute "effective_rate"
     */
    public function testPropertyEffectiveRate()
    {
    }

    /**
     * Test attribute "monthly_payment"
     */
    public function testPropertyMonthlyPayment()
    {
    }

    /**
     * Test attribute "desposit_percentage"
     */
    public function testPropertyDespositPercentage()
    {
    }

    /**
     * Test attribute "total_billing_cycles"
     */
    public function testPropertyTotalBillingCycles()
    {
    }

    /**
     * Test attribute "default_term"
     */
    public function testPropertyDefaultTerm()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }
}
