<?php
/**
 * PaymentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1PaymentsAllByOrderRefMerchantsByMerchantIdSitesByMerchantSiteIdGet
     *
     * Gets ALL the details for a specified OrderRef..
     *
     */
    public function testV1PaymentsAllByOrderRefMerchantsByMerchantIdSitesByMerchantSiteIdGet()
    {
    }

    /**
     * Test case for v1PaymentsByOrderRefMerchantsByMerchantIdSitesByMerchantSiteIdByOrderTagGet
     *
     * Gets the details for a specified couple of OrderRef/OrderTag..
     *
     */
    public function testV1PaymentsByOrderRefMerchantsByMerchantIdSitesByMerchantSiteIdByOrderTagGet()
    {
    }

    /**
     * Test case for v1PaymentsByOrderRefMerchantsByMerchantIdSitesByMerchantSiteIdGet
     *
     * Gets the details for a specified OrderRef..
     *
     */
    public function testV1PaymentsByOrderRefMerchantsByMerchantIdSitesByMerchantSiteIdGet()
    {
    }

    /**
     * Test case for v1PaymentsByOrderRefOperationsCancelOrRefundPut
     *
     * Executes a cancel or refund operation on the specified OrderRef..
     *
     */
    public function testV1PaymentsByOrderRefOperationsCancelOrRefundPut()
    {
    }

    /**
     * Test case for v1PaymentsByOrderRefOperationsCapturePut
     *
     * Executes a capture operation on the specified OrderRef..
     *
     */
    public function testV1PaymentsByOrderRefOperationsCapturePut()
    {
    }

    /**
     * Test case for v1PaymentsByOrderRefOperationsRecomputePut
     *
     * Executes a recompute operation on the specified OrderRef..
     *
     */
    public function testV1PaymentsByOrderRefOperationsRecomputePut()
    {
    }
}
